// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Application struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	Job       string `json:"job"`
}

type Job struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	JoinLocation string `json:"joinLocation"`
	CreatedBy    string `json:"createdBy"`
}

type NewApplication struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	JobID     string `json:"jobID"`
}

type NewJob struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	JoinLocation string `json:"joinLocation"`
	CreatedByID  string `json:"createdByID"`
}

type UpdateJob struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	JoinLocation string `json:"joinLocation"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
